language: ruby
rvm:
  - 2.4.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
bundler_args: --binstubs=./bundler_stubs
